import math
import numpy as np
from typing import List
from models import CandidateProfile, ProjectProfile, TeamCompositionResult

def calculate_activation_energy(team: List[CandidateProfile]) -> float:
    """Return the mean activation_energy across all team members"""
    if not team: return 0.0
    return float(np.mean([c.activation_energy for c in team]))

def calculate_catalytic_coefficient(team: List[CandidateProfile]) -> float:
    """Return the mean catalytic_rating, boosted by 0.1 for each person with catalytic_rating > 0.8."""
    if not team: return 0.0
    base = float(np.mean([c.catalytic_rating for c in team]))
    boost = sum(0.1 for c in team if c.catalytic_rating > 0.8)
    return base + boost

def calculate_role_complementarity(team: List[CandidateProfile], required_roles: List[str]) -> float:
    """Check what fraction of required_roles are covered by the team's role_types..."""
    if not required_roles: return 1.0
    covered_roles = [c.role_type for c in team]
    
    # We map roles covered to roles required. E.g. if required_roles = ['engineer', 'engineer'], we need 2 engineers.
    # Simple check: fraction of standard roles covered. 
    # To properly count frequencies, let's use a copy of covered
    covered_copy = list(covered_roles)
    coverage_count = 0
    for req in required_roles:
        if req in covered_copy:
            coverage_count += 1
            covered_copy.remove(req)
            
    score = coverage_count / len(required_roles)
    
    # valency check: Valency implies max productive relationships. We'll compare it to team size - 1 as a heuristic.
    required_relationships = len(team) - 1
    penalty = sum(0.05 for c in team if c.role_valency < required_relationships)
    
    score -= penalty
    return max(0.0, min(1.0, score))

def calculate_reaction_rate(team: List[CandidateProfile], project: ProjectProfile) -> float:
    """Implement adapted Arrhenius: Rate = A * exp(-Ea / (R * T))"""
    if not team: return 0.0
    A = calculate_catalytic_coefficient(team)
    Ea = calculate_activation_energy(team)
    R = calculate_role_complementarity(team, project.required_roles)
    T = project.temperature
    
    if R == 0 or T == 0:
        rate = 0.0
    else:
        exponent = -Ea / (R * T)
        rate = A * math.exp(exponent)
        
    # Normalize output to 0.0-1.0 range using a sigmoid function
    def sigmoid(x):
        return 1 / (1 + math.exp(-x))
        
    return sigmoid(rate)

def calculate_yield_score(team: List[CandidateProfile], project: ProjectProfile, inhibition_graph) -> float:
    import inhibition_graph as ig
    target = project.yield_requirement
    pairs = ig.get_inhibition_pairs(team, inhibition_graph)
    drag = ig.get_drag_coefficient(pairs)
    
    if project.reaction_type == 'chain':
        drag *= 1.5
        
    score = target - drag
    return max(0.0, min(1.0, score))

def calculate_stability_score(team: List[CandidateProfile], project: ProjectProfile) -> float:
    if not team: return 0.0
    # Average stability over the team. Higher projects weight it more heavily later.
    return float(np.mean([c.thermal_stability for c in team]))

def score_team(team: List[CandidateProfile], project: ProjectProfile, inhibition_graph) -> TeamCompositionResult:
    rate = calculate_reaction_rate(team, project)
    yield_sc = calculate_yield_score(team, project, inhibition_graph)
    stability = calculate_stability_score(team, project)
    
    composite = 0.4 * rate + 0.35 * yield_sc + 0.25 * stability
    
    explanations = {
        "reaction_rate": f"Arrhenius rate generated by combining Activation Energy and Catalytic Coefficients.",
        "yield_score": f"Driven by inhibition pairs in graph against the yield requirement.",
        "stability_score": f"Stability based on average thermal robustness across conditions.",
        "composite_score": f"Weighted by organizational factors."
    }
    
    return TeamCompositionResult(
        team=team,
        reaction_rate=rate,
        yield_score=yield_sc,
        stability_score=stability,
        composite_score=composite,
        explanation=explanations
    )
